# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Mod Properties (shared across all versions)
mod_version=1.0-SNAPSHOT
maven_group=ru.kseonyt
archives_base_name=Chained
# Default Fabric Properties (version-specific properties are in versions/*/gradle.properties)
# check these on https://modmuss50.me/fabric.html
loader_version=0.18.1
