pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'KikuGie Snapshots'
            url = 'https://maven.kikugie.dev/snapshots'
        }
        gradlePluginPortal()
    }
}

plugins {
    id 'dev.kikugie.stonecutter' version '0.7.11'
}

stonecutter {
    kotlinController = false
    centralScript = 'build.gradle'
    
    create(rootProject) {
        versions '1.21.4', '1.21.8', '1.21.9', '1.21.10'
    }
}
